CREATE DATABASE  IF NOT EXISTS `leonteqdb`;
USE `leonteqdb`;


DROP TABLE IF EXISTS `authorities`;
CREATE TABLE `authorities` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUTHORITY` varchar(100) NOT NULL,
  `SHORT_AUTHORITY` varchar(50) NOT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SHORT_AUTHORITY_UNIQUE` (`SHORT_AUTHORITY`),
  UNIQUE KEY `AUTHORITY_UNIQUE` (`AUTHORITY`)
) ENGINE=InnoDB;


DROP TABLE IF EXISTS `path_conversion`;
CREATE TABLE `path_conversion` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LONG_PATH` text NOT NULL,
  `SHORT_PATH` varchar(200) NOT NULL,
  `CREATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;
